import type { ConfigType, FieldDefinition } from './types'

export type ConfigDefinition = { id: ConfigType; label: string; group: string; description: string; fields: FieldDefinition[] }

export const configDefinitions: ConfigDefinition[] = [
  { id: 'vlan', label: 'VLAN', group: 'Switching', description: 'Create a named VLAN on the switch.', fields: [{ key: 'vlanId', label: 'VLAN ID', placeholder: 'e.g. 20', type: 'number' }, { key: 'vlanName', label: 'VLAN Name', placeholder: 'e.g. OPERATIONS' }] },
  { id: 'access-port', label: 'Access Port', group: 'Switching', description: 'Assign a switch interface to an access VLAN.', fields: [{ key: 'interface', label: 'Interface', placeholder: 'e.g. GigabitEthernet0/1' }, { key: 'vlanId', label: 'VLAN ID', placeholder: 'e.g. 20', type: 'number' }] },
  { id: 'trunk', label: 'Trunk', group: 'Switching', description: 'Configure an 802.1Q trunk interface.', fields: [{ key: 'interface', label: 'Interface', placeholder: 'e.g. GigabitEthernet0/24' }, { key: 'allowedVlan', label: 'Allowed VLAN', placeholder: 'e.g. 10,20,30' }] },
  { id: 'inter-vlan', label: 'Inter-VLAN', group: 'Routing', description: 'Create a router-on-a-stick sub-interface.', fields: [{ key: 'interface', label: 'Interface', placeholder: 'e.g. GigabitEthernet0/0.20' }, { key: 'vlanId', label: 'VLAN ID', placeholder: 'e.g. 20', type: 'number' }, { key: 'ipAddress', label: 'IP Address', placeholder: 'e.g. 192.168.20.1' }, { key: 'subnetMask', label: 'Subnet Mask', placeholder: 'e.g. 255.255.255.0' }] },
  { id: 'dhcp', label: 'DHCP', group: 'Services', description: 'Set up a local DHCP pool.', fields: [{ key: 'poolName', label: 'Pool Name', placeholder: 'e.g. USERS' }, { key: 'network', label: 'Network', placeholder: 'e.g. 192.168.10.0' }, { key: 'subnetMask', label: 'Subnet Mask', placeholder: 'e.g. 255.255.255.0' }, { key: 'defaultGateway', label: 'Default Gateway', placeholder: 'e.g. 192.168.10.1' }, { key: 'dnsServer', label: 'DNS Server', placeholder: 'e.g. 8.8.8.8' }] },
  { id: 'static-routing', label: 'Static Routing', group: 'Routing', description: 'Add a static route to the routing table.', fields: [{ key: 'network', label: 'Network', placeholder: 'e.g. 10.10.0.0' }, { key: 'subnetMask', label: 'Subnet Mask', placeholder: 'e.g. 255.255.255.0' }, { key: 'nextHop', label: 'Next Hop', placeholder: 'e.g. 192.168.1.2' }] },
  { id: 'ospf', label: 'OSPF', group: 'Routing', description: 'Advertise a network through OSPF.', fields: [{ key: 'processId', label: 'Process ID', placeholder: 'e.g. 1', type: 'number' }, { key: 'network', label: 'Network', placeholder: 'e.g. 10.0.0.0' }, { key: 'wildcard', label: 'Wildcard', placeholder: 'e.g. 0.0.0.255' }, { key: 'area', label: 'Area', placeholder: 'e.g. 0', type: 'number' }] },
  { id: 'eigrp', label: 'EIGRP', group: 'Routing', description: 'Enable classic EIGRP for a network.', fields: [{ key: 'asNumber', label: 'AS Number', placeholder: 'e.g. 100', type: 'number' }, { key: 'network', label: 'Network', placeholder: 'e.g. 192.168.10.0' }, { key: 'wildcard', label: 'Wildcard', placeholder: 'e.g. 0.0.0.255' }] },
  { id: 'bgp', label: 'BGP', group: 'Routing', description: 'Configure an external BGP neighbor.', fields: [{ key: 'localAs', label: 'Local AS', placeholder: 'e.g. 65001', type: 'number' }, { key: 'neighborIp', label: 'Neighbor IP', placeholder: 'e.g. 203.0.113.2' }, { key: 'neighborAs', label: 'Neighbor AS', placeholder: 'e.g. 65002', type: 'number' }] },
  { id: 'nat', label: 'NAT', group: 'Security', description: 'Choose a NAT pattern and generate its base commands.', fields: [{ key: 'natType', label: 'NAT Type', placeholder: 'Select a mode', type: 'select', options: ['Static NAT', 'Dynamic NAT', 'PAT'] }] },
  { id: 'acl', label: 'ACL', group: 'Security', description: 'Build a standard or extended ACL shell.', fields: [{ key: 'aclType', label: 'ACL Type', placeholder: 'Select an ACL type', type: 'select', options: ['Standard ACL', 'Extended ACL'] }] },
  { id: 'port-security', label: 'Port Security', group: 'Security', description: 'Lock down an access port with MAC limits.', fields: [{ key: 'interface', label: 'Interface', placeholder: 'e.g. GigabitEthernet0/5' }, { key: 'maximumMac', label: 'Maximum MAC', placeholder: 'e.g. 2', type: 'number' }, { key: 'violationMode', label: 'Violation Mode', placeholder: 'Select a mode', type: 'select', options: ['shutdown', 'restrict', 'protect'] }] },
  { id: 'etherchannel', label: 'EtherChannel', group: 'Switching', description: 'Bundle interfaces into a port-channel.', fields: [{ key: 'interfaceRange', label: 'Interface Range', placeholder: 'e.g. Gi0/1 - 2' }, { key: 'channelGroup', label: 'Channel Group', placeholder: 'e.g. 1', type: 'number' }, { key: 'mode', label: 'Mode', placeholder: 'Select a mode', type: 'select', options: ['active', 'passive', 'on'] }] },
]

export const getDefinition = (id: ConfigType) => configDefinitions.find((definition) => definition.id === id)!